### ISSUE TITLE
Proposal: Do not expose NSURLSessionDataTask in Client API.

### ISSUE THREAD

**Issue by mtnbarreto** [faunadb/faunadb-swift#46]
Eventually we might want to change networking library that currently relies on NSURLSession and NSURLSessionDataTask which are specific Foundation networking abstractions. 
In our current implementation we are returning the task as a result of client.query method to be able to cancel the request, which is something thats happens often in a mobile platform as Example app shows. 

Maybe we should wrap it up as `CancelableQueryRequest` type. 

``` swift
protocol CancelableQueryRequest {
    func cancel()
}
```

extension NSURLSessionDataTask: CancelableQueryRequest {}

@erickpintor Let me know if you think this is necessary.

**Comment by erickpintor** [comment]
Not needed anymore.
