### ISSUE TITLE
Automate framework binary creation for all platforms and attach them to github release

### ISSUE THREAD

**Issue by mtnbarreto** [faunadb/faunadb-swift#67]
https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-one-zip-file

Benefits: 
1. Speed up dependency integration through carthage.
2. Binaries can be used directly. User will not need to clone the repository to build the sdk.
3. Clean driver versioning. Binaries availability.

**Comment by erickpintor** [comment]
Wontfix.
